[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
python_files = "test_*.py"
markers = [
    "asyncio: mark asyncio tests",
    "slow: slow running tests"
]

[tool.pytest.ini_options.asyncio]
default_fixture_loop_scope = "function"
default_test_loop_scope = "function"
